
use GoGo

insert into City (CityName) values ('Vashkivtsi');
insert into City (CityName) values ('Laem Sing');
insert into City (CityName) values ('Baicaogou');
insert into City (CityName) values ('Além Paraíba');
insert into City (CityName) values ('Singida');
insert into City (CityName) values ('Zaoshi');
insert into City (CityName) values ('Gwanda');
insert into City (CityName) values ('Minggang');
insert into City (CityName) values ('Ampelókipoi');
insert into City (CityName) values ('Żabno');
insert into City (CityName) values ('Wangcheng');
insert into City (CityName) values ('East End');
insert into City (CityName) values ('Cipadung Timur');
insert into City (CityName) values ('Recarei');
insert into City (CityName) values ('Donegal');
insert into City (CityName) values ('Saaban');
insert into City (CityName) values ('Ballyboden');
insert into City (CityName) values ('Kushima');
insert into City (CityName) values ('Lloque');
insert into City (CityName) values ('Concordia');
insert into City (CityName) values ('Emiliano Zapata');
insert into City (CityName) values ('Quitilipi');
insert into City (CityName) values ('Los Andes');
insert into City (CityName) values ('Oslo');
insert into City (CityName) values ('Buchanan');
insert into City (CityName) values ('Goroka');
insert into City (CityName) values ('Zdenci');
insert into City (CityName) values ('Cavan');
insert into City (CityName) values ('Jixiang');
insert into City (CityName) values ('Lebane');
insert into City (CityName) values ('Sukojember');
insert into City (CityName) values ('Balyqshy');
insert into City (CityName) values ('Springfield');
insert into City (CityName) values ('Hedong');
insert into City (CityName) values ('Longmenfan');
insert into City (CityName) values ('Zhengmo');
insert into City (CityName) values ('Shaogongzhuang');
insert into City (CityName) values ('Molodohvardiys’k');
insert into City (CityName) values ('Proletar');
insert into City (CityName) values ('Amiens');
insert into City (CityName) values ('Kanthararom');
insert into City (CityName) values ('Dujuuma');
insert into City (CityName) values ('Paris 15');
insert into City (CityName) values ('Dongshui');
insert into City (CityName) values ('Luokeng');
insert into City (CityName) values ('Tucano');
insert into City (CityName) values ('Tsuyama');
insert into City (CityName) values ('Kruševo');
insert into City (CityName) values ('Goragorskiy');
insert into City (CityName) values ('Oslo');
insert into City (CityName) values ('Ningmute');
insert into City (CityName) values ('Askeaton');
insert into City (CityName) values ('Yao');
insert into City (CityName) values ('Dagang');
insert into City (CityName) values ('Yalagüina');
insert into City (CityName) values ('Baleal');
insert into City (CityName) values ('Phatthana Nikhom');
insert into City (CityName) values ('Florentino Ameghino');
insert into City (CityName) values ('Conceição do Araguaia');
insert into City (CityName) values ('Tianxing');
insert into City (CityName) values ('Kwikila');
insert into City (CityName) values ('Gaspar');
insert into City (CityName) values ('Petrovskiy');
insert into City (CityName) values ('Hidalgo');
insert into City (CityName) values ('Aix-en-Provence');
insert into City (CityName) values ('Enköping');
insert into City (CityName) values ('Newton');
insert into City (CityName) values ('Kikerino');
insert into City (CityName) values ('Chamlykskaya');
insert into City (CityName) values ('Leigongjian');
insert into City (CityName) values ('Borås');
insert into City (CityName) values ('Brandýs nad');
insert into City (CityName) values ('Guradog');
insert into City (CityName) values ('Kafr az Zayyāt');
insert into City (CityName) values ('Zhangcun');
insert into City (CityName) values ('Meikeng');
insert into City (CityName) values ('Koncang');
insert into City (CityName) values ('Vinhedo');
insert into City (CityName) values ('Ailigandí');
insert into City (CityName) values ('Antalaha');
insert into City (CityName) values ('Las Breñas');
insert into City (CityName) values ('Thāru Shāh');
insert into City (CityName) values ('Vorob’yovo');
insert into City (CityName) values ('Sindangsuka');
insert into City (CityName) values ('Yichun');
insert into City (CityName) values ('Wakema');
insert into City (CityName) values ('Yinglong');
insert into City (CityName) values ('Bontoc');
insert into City (CityName) values ('Kruty');
insert into City (CityName) values ('Xinjie');
insert into City (CityName) values ('Saint John');
insert into City (CityName) values ('Bridgetown');
insert into City (CityName) values ('Gaotang');
insert into City (CityName) values ('Kobelyaky');
insert into City (CityName) values ('Veselí nad Lužnicí');
insert into City (CityName) values ('Nobo');
insert into City (CityName) values ('Roshal’');
insert into City (CityName) values ('Biecz');
insert into City (CityName) values ('Zuogaiduoma');
insert into City (CityName) values ('Regla');
insert into City (CityName) values ('Ånge');
insert into City (CityName) values ('Sohbatpur');
insert into City (CityName) values ('Penisihan');
insert into City (CityName) values ('Cruz');
insert into City (CityName) values ('Al Ḩāmūl');
insert into City (CityName) values ('Zeerust');
insert into City (CityName) values ('Libertador General San Martín');
insert into City (CityName) values ('Pazin');
insert into City (CityName) values ('Begejci');
insert into City (CityName) values ('Corona');
insert into City (CityName) values ('Abengourou');
insert into City (CityName) values ('Upig');
insert into City (CityName) values ('Banjar Peguyangan');
insert into City (CityName) values ('Chiang Yuen');
insert into City (CityName) values ('Sbo’o');
insert into City (CityName) values ('Nangang');
insert into City (CityName) values ('Probolinggo');
insert into City (CityName) values ('Náchod');
insert into City (CityName) values ('El Soberbio');
insert into City (CityName) values ('Lunik');
insert into City (CityName) values ('Lamut');
insert into City (CityName) values ('Grenoble');
insert into City (CityName) values ('Kizema');
insert into City (CityName) values ('Guniushan');
insert into City (CityName) values ('San Nicolás');
insert into City (CityName) values ('Kuala Lumpur');
insert into City (CityName) values ('New York City');
insert into City (CityName) values ('Amaigbo');
insert into City (CityName) values ('Xiayang');
insert into City (CityName) values ('Pataypampa');
insert into City (CityName) values ('Essang');
insert into City (CityName) values ('Piúma');
insert into City (CityName) values ('Warri');
insert into City (CityName) values ('Manola');
insert into City (CityName) values ('Brändö');
insert into City (CityName) values ('Sabaneta');
insert into City (CityName) values ('Qalqīlyah');
insert into City (CityName) values ('Sanxi');
insert into City (CityName) values ('Poiares');
insert into City (CityName) values ('La Oroya');
insert into City (CityName) values ('Cikeusal');
insert into City (CityName) values ('Tōgane');
insert into City (CityName) values ('Nagoselo do Douro');
insert into City (CityName) values ('Étampes');
insert into City (CityName) values ('San Manuel');
insert into City (CityName) values ('Los Patios');
insert into City (CityName) values ('Lộc Bình');
insert into City (CityName) values ('São Pedro');
insert into City (CityName) values ('Ágios Vasíleios');
insert into City (CityName) values ('Bishkek');
insert into City (CityName) values ('Guayabal');
insert into City (CityName) values ('Pimenta Bueno');
insert into City (CityName) values ('Spitak');
insert into City (CityName) values ('Dayton');
insert into City (CityName) values ('Indaial');
insert into City (CityName) values ('Dhaka');
insert into City (CityName) values ('Langarūd');
insert into City (CityName) values ('Mari');
insert into City (CityName) values ('Puncakwangi');
insert into City (CityName) values ('Enyerhyetykaw');
insert into City (CityName) values ('Banjar Tengah');
insert into City (CityName) values ('Qaşr al Farāfirah');
insert into City (CityName) values ('Al Khānkah');
insert into City (CityName) values ('Yidu');
insert into City (CityName) values ('Xiaoguwei');
insert into City (CityName) values ('Tangwu');
insert into City (CityName) values ('Kutampi');
insert into City (CityName) values ('Mulino');
insert into City (CityName) values ('Puerto Iguazú');
insert into City (CityName) values ('Şurmān');
insert into City (CityName) values ('Tangfang');
insert into City (CityName) values ('Guilhabreu');
insert into City (CityName) values ('Áno Kómi');
insert into City (CityName) values ('Coromoro');
insert into City (CityName) values ('Yanghu');
insert into City (CityName) values ('Opol');
insert into City (CityName) values ('Macaíba');
insert into City (CityName) values ('Dapuchaihe');
insert into City (CityName) values ('Bulgan');
insert into City (CityName) values ('Tlogocilik');
insert into City (CityName) values ('Juan Adrián');
insert into City (CityName) values ('Talabaan');
insert into City (CityName) values ('Santana do Livramento');
insert into City (CityName) values ('Kampungbaru');
insert into City (CityName) values ('Massenya');
insert into City (CityName) values ('Tongjing');
insert into City (CityName) values ('Ḩātim');
insert into City (CityName) values ('Laolong');
insert into City (CityName) values ('Tengqiao');
insert into City (CityName) values ('Boundiali');
insert into City (CityName) values ('Tai’an');
insert into City (CityName) values ('Banjar Buahan');
insert into City (CityName) values ('Trondheim');
insert into City (CityName) values ('Hato Mayor del Rey');
insert into City (CityName) values ('Banjar Penyalin');
insert into City (CityName) values ('Devin');
insert into City (CityName) values ('Idi Rayeuk');
insert into City (CityName) values ('Słońsk');
insert into City (CityName) values ('Havířov');
insert into City (CityName) values ('Kongkeshu');
