use GoGo
select * from City

insert into City(CityName,LastCreatedDate,LastModifiedDate,IsDeleted) values (N'TP Hồ Chí Minh',GETDATE(),GETDATE(),0)
insert into City(CityName,LastCreatedDate,LastModifiedDate,IsDeleted) values (N'Long An',GETDATE(),GETDATE(),0)
insert into City(CityName,LastCreatedDate,LastModifiedDate,IsDeleted) values (N'Đồng Tháp',GETDATE(),GETDATE(),0)
insert into City(CityName,LastCreatedDate,LastModifiedDate,IsDeleted) values (N'Tiền Giang',GETDATE(),GETDATE(),0)
insert into City(CityName,LastCreatedDate,LastModifiedDate,IsDeleted) values (N'Bến Tre',GETDATE(),GETDATE(),0)
insert into City(CityName,LastCreatedDate,LastModifiedDate,IsDeleted) values (N'Trà Vinh',GETDATE(),GETDATE(),0)
insert into City(CityName,LastCreatedDate,LastModifiedDate,IsDeleted) values (N'Vĩnh Long',GETDATE(),GETDATE(),0)
insert into City(CityName,LastCreatedDate,LastModifiedDate,IsDeleted) values (N'Hậu Giang',GETDATE(),GETDATE(),0)
insert into City(CityName,LastCreatedDate,LastModifiedDate,IsDeleted) values (N'Cần thơ',GETDATE(),GETDATE(),0)

select * from District

insert into District(DistrictName,CityId,LastCreatedDate, LastModifiedDate, IsDeleted) values (N'Gò Vấp',1,GETDATE(),GETDATE(),0)
insert into District(DistrictName,CityId,LastCreatedDate, LastModifiedDate, IsDeleted) values (N'Bình Tân',1,GETDATE(),GETDATE(),0)
insert into District(DistrictName,CityId,LastCreatedDate, LastModifiedDate, IsDeleted) values (N'Phú Nhuận',1,GETDATE(),GETDATE(),0)
insert into District(DistrictName,CityId,LastCreatedDate, LastModifiedDate, IsDeleted) values (N'Thủ Đức',1,GETDATE(),GETDATE(),0)
insert into District(DistrictName,CityId,LastCreatedDate, LastModifiedDate, IsDeleted) values (N'Tân Bình',1,GETDATE(),GETDATE(),0)
insert into District(DistrictName,CityId,LastCreatedDate, LastModifiedDate, IsDeleted) values (N'Tân Phú',1,GETDATE(),GETDATE(),0)
insert into District(DistrictName,CityId,LastCreatedDate, LastModifiedDate, IsDeleted) values (N'Bình Chánh',1,GETDATE(),GETDATE(),0)
insert into District(DistrictName,CityId,LastCreatedDate, LastModifiedDate, IsDeleted) values (N'1',1,GETDATE(),GETDATE(),0)
insert into District(DistrictName,CityId,LastCreatedDate, LastModifiedDate, IsDeleted) values (N'2',1,GETDATE(),GETDATE(),0)
insert into District(DistrictName,CityId,LastCreatedDate, LastModifiedDate, IsDeleted) values (N'3',1,GETDATE(),GETDATE(),0)
insert into District(DistrictName,CityId,LastCreatedDate, LastModifiedDate, IsDeleted) values (N'4',1,GETDATE(),GETDATE(),0)
insert into District(DistrictName,CityId,LastCreatedDate, LastModifiedDate, IsDeleted) values (N'5',1,GETDATE(),GETDATE(),0)
insert into District(DistrictName,CityId,LastCreatedDate, LastModifiedDate, IsDeleted) values (N'6',1,GETDATE(),GETDATE(),0)
insert into District(DistrictName,CityId,LastCreatedDate, LastModifiedDate, IsDeleted) values (N'7',1,GETDATE(),GETDATE(),0)
insert into District(DistrictName,CityId,LastCreatedDate, LastModifiedDate, IsDeleted) values (N'8',1,GETDATE(),GETDATE(),0)
insert into District(DistrictName,CityId,LastCreatedDate, LastModifiedDate, IsDeleted) values (N'9',1,GETDATE(),GETDATE(),0)
insert into District(DistrictName,CityId,LastCreatedDate, LastModifiedDate, IsDeleted) values (N'10',1,GETDATE(),GETDATE(),0)
insert into District(DistrictName,CityId,LastCreatedDate, LastModifiedDate, IsDeleted) values (N'11',1,GETDATE(),GETDATE(),0)
insert into District(DistrictName,CityId,LastCreatedDate, LastModifiedDate, IsDeleted) values (N'12',1,GETDATE(),GETDATE(),0)

insert into District(DistrictName,CityId,LastCreatedDate, LastModifiedDate, IsDeleted) values (N'Đức Huệ',2,GETDATE(),GETDATE(),0)
insert into District(DistrictName,CityId,LastCreatedDate, LastModifiedDate, IsDeleted) values (N'Đức Hòa',2,GETDATE(),GETDATE(),0)
insert into District(DistrictName,CityId,LastCreatedDate, LastModifiedDate, IsDeleted) values (N'Châu Thành',2,GETDATE(),GETDATE(),0)
insert into District(DistrictName,CityId,LastCreatedDate, LastModifiedDate, IsDeleted) values (N'Mộc Hóa',2,GETDATE(),GETDATE(),0)
insert into District(DistrictName,CityId,LastCreatedDate, LastModifiedDate, IsDeleted) values (N'Bến Lức',2,GETDATE(),GETDATE(),0)

insert into District(DistrictName,CityId,LastCreatedDate, LastModifiedDate, IsDeleted) values (N'Cao Lãnh',3,GETDATE(),GETDATE(),0)
insert into District(DistrictName,CityId,LastCreatedDate, LastModifiedDate, IsDeleted) values (N'Hồng Ngự',3,GETDATE(),GETDATE(),0)
insert into District(DistrictName,CityId,LastCreatedDate, LastModifiedDate, IsDeleted) values (N'Châu Thành',3,GETDATE(),GETDATE(),0)
insert into District(DistrictName,CityId,LastCreatedDate, LastModifiedDate, IsDeleted) values (N'Lai Vung',3,GETDATE(),GETDATE(),0)

insert into District(DistrictName,CityId,LastCreatedDate, LastModifiedDate, IsDeleted) values (N'Cai Lậy',4,GETDATE(),GETDATE(),0)
insert into District(DistrictName,CityId,LastCreatedDate, LastModifiedDate, IsDeleted) values (N'Cái Bè',4,GETDATE(),GETDATE(),0)
insert into District(DistrictName,CityId,LastCreatedDate, LastModifiedDate, IsDeleted) values (N'Châu Thành',4,GETDATE(),GETDATE(),0)
insert into District(DistrictName,CityId,LastCreatedDate, LastModifiedDate, IsDeleted) values (N'Chợ Gạo',4,GETDATE(),GETDATE(),0)
insert into District(DistrictName,CityId,LastCreatedDate, LastModifiedDate, IsDeleted) values (N'Gò Công',4,GETDATE(),GETDATE(),0)
insert into District(DistrictName,CityId,LastCreatedDate, LastModifiedDate, IsDeleted) values (N'Mỹ Tho',4,GETDATE(),GETDATE(),0)
